#%RAML 0.8
title: Cakeshop View Controller API
baseUri: http://localhost:8080/example-query-controller/query/controller/rest/cakeshop
version: v0.1
mediaType: application/json
protocols: [ HTTP, HTTPS ]

/recipes:
  description: list all recipes
  get:
    description: |
        ...
        (mapping):
            responseType: application/vnd.example.recipes+json
            name: example.search-recipes
        ...
    queryParameters:
        pagesize:
            type: integer
            required: true
        name:
          displayName: Name
          type: string
          description: A recipe name
          example: Mess
          required: false
        glutenFree:
            type: boolean
            required: false
    responses:
      200:
        body:
          application/vnd.example.recipes+json:
            schema: !include json/schema/example.search-recipes.json
            example: !include json/recipes.json

/recipes/{recipeId}:
  description: return a recipe
  get:
    description: |
        ...
        (mapping):
            responseType: application/vnd.example.recipe+json
            name: example.get-recipe
        ...
    responses:
      200:
        body:
          application/vnd.example.recipe+json:
            schema: !include json/schema/example.get-recipe.json
            example: !include json/recipe.json


/orders/{orderId}:
  description: return a recipe
  get:
    description: |
        ...
        (mapping):
            responseType: application/vnd.example.order+json
            name: example.get-order
        ...
    responses:
      200:
        body:
          application/vnd.example.order+json:
            schema: !include json/schema/example.get-order.json
            example: !include json/order.json