#%RAML 0.8
title: API Using media type in the URL
baseUri: message://command/handler/message/cakeshop
version: v1
/cakeshop.handler.command:
  post:
    body:
        application/vnd.cakeshop.command.add-recipe+json:
            schema: !include json/schema/cakeshop.command.add-recipe.json
            example: !include json/add-recipe.json

        application/vnd.cakeshop.command.add-recipe-transacted+json:
            schema: !include json/schema/cakeshop.command.add-recipe-transacted.json
            example: !include json/add-recipe-transacted.json

        application/vnd.cakeshop.command.make-cake+json:
            schema: !include json/schema/cakeshop.command.make-cake.json
            example: !include json/make-cake.json
