#%RAML 0.8
title: API Using media type in the URL
version: v1
/cakeshop.handler.command:
  post:
    body:
        application/vnd.cakeshop.command.add-recipe+json:
            schema: !include json/schema/add-recipe.json
            example: !include json/add-recipe.json

        application/vnd.cakeshop.command.make-cake+json:
            schema: !include json/schema/make-cake.json
            example: !include json/make-cake.json