#%RAML 0.8
title: Event Source API
baseUri: http://localhost:8080/event-source-api/rest
version: v0.1
mediaType: application/json
protocols: [ HTTP, HTTPS ]

/event-streams/{position}/{direction}/{pageSize}
  description: paginated page listing all event streams
  get:
    queryParameters:
        page:
            type: integer
            required: false
            description: page number
    responses:
      200:
        body:
          application/vnd.event-source.event-streams+json:
            schema: !include json/schema/event-source.event-streams.json
            example: !include json/event-source.event-streams.json

/event-streams/{streamId}/{position}/{direction}/{pageSize}
  description: paginated page listing all events in the stream
  get:
    responses:
      200:
        body:
          application/vnd.event-source.events+json:
            schema: !include json/schema/event-source.event-stream.json
            example: !include json/event-source.event-stream.json