#%RAML 0.8
title: Cakeshop Command API
baseUri: http://localhost:8080/example-command-api/command/api/rest/cakeshop
version: v0.1
mediaType: application/json
protocols: [ HTTP, HTTPS ]

/recipes/{recipeId}:
  description: |
    Add a new recipe
  post:
    description: |
        ...
        (mapping):
            requestType: application/vnd.example.add-recipe+json
            name: example.add-recipe
        (mapping):
            requestType: application/vnd.example.remove-recipe+json
            name: example.remove-recipe
        (mapping):
            requestType: application/vnd.example.add-recipe-file+json
            name: example.add-recipe-file
        ...

    body:
        application/vnd.example.add-recipe+json:
            schema: !include json/schema/command_api/example.add-recipe.json
            example: !include json/add-recipe.json

        application/vnd.example.remove-recipe+json: !!null

        application/vnd.example.add-recipe-file+json:
            schema: !include json/schema/command_api/example.add-recipe-file.json
            example: !include json/add-recipe-file.json

  put:
    description: |
        ...
        (mapping):
            requestType: application/vnd.example.rename-recipe+json
            name: example.rename-recipe
        ...

    body:
        application/vnd.example.rename-recipe+json:
            schema: !include json/schema/command_api/example.rename-recipe.json
            example: !include json/rename-recipe.json


/recipes/{recipeId}/cakes/{cakeId}:
  description: |
    Make a cake from id in json
  post:
    description: |
        ...
        (mapping):
            requestType: application/vnd.example.make-cake+json
            name: example.make-cake
        ...
    body:
        application/vnd.example.make-cake+json:
            schema: !include json/schema/command_api/example.make-cake.json
            example: !include json/make-cake.json



/orders/{orderId}:
  description: |
    Order a cake
  post:
    description: |
        ...
        (mapping):
            requestType: application/vnd.example.order-cake+json
            name: example.order-cake
        ...
    body:
        application/vnd.example.order-cake+json:
            schema: !include json/schema/command_api/example.order-cake.json
            example: !include json/order-cake.json

/recipes/{recipeId}/photograph:
  post:
    description: |
      Upload recipe photograph
      ...
      (mapping):
          requestType: multipart/form-data
          name: example.upload-photograph
      ...
    body:
     multipart/form-data:
      formParameters:
        photoId:
          description: Photo of recipe
          type: file
    responses:
      202:
        description: Request accepted
      400:
        description: Bad Request
      500:
        description: Internal Server Error
