#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/listener/message/cakeshop
version: v1
/example.event:
  post:
    body:
        application/vnd.example.recipe-added+json:
            schema: !include json/schema/example.recipe-added.json
            example: !include json/add-recipe.json

        application/vnd.example.recipe-removed+json:
            schema: !include json/schema/example.recipe-removed.json
            example: !include json/recipe-removed.json

        application/vnd.example.cake-made+json:
            schema: !include json/schema/example.cake-made.json
            example: !include json/make-cake.json

        application/vnd.example.cake-ordered+json:

        application/vnd.example.recipe-renamed+json:
                    schema: !include json/schema/example.recipe-renamed.json
                    example: !include json/recipe-renamed.json