#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/listener/message/cakeshop
version: v1
/cakeshop.event:
  post:
    body:
        application/vnd.cakeshop.event.recipe-added+json:
            schema: !include json/schema/add-recipe.json
            example: !include json/add-recipe.json

        application/vnd.cakeshop.event.cake-made+json:
            schema: !include json/schema/make-cake.json
            example: !include json/make-cake.json