#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/listener/message/cakeshop
version: v1
/cakeshop.event:
  post:
    body:
        application/vnd.cakeshop.recipe-added+json:
            schema: !include json/schema/cakeshop.recipe-added.json
            example: !include json/add-recipe.json

        application/vnd.cakeshop.cake-made+json:
            schema: !include json/schema/cakeshop.cake-made.json
            example: !include json/make-cake.json