#%RAML 0.8
title: API Using media type in the URL
baseUri: message://command/controller/message/service1
version: v1

/contexta.controller.command:
  post:
    body:
        application/vnd.contexta.commanda+json:
