#%RAML 0.8
title: API Using media type in the URL
baseUri: message://command/controller/message/service1
version: v1

/structure.controller.command:
  post:
    body:
        application/vnd.structure.commanda+json:
            schema: !include json/schema/structure.commanda.json
            example: !include json/cmdaa.json
        application/vnd.structure.commandb+json:
            schema: !include json/schema/structure.commandb.json
            example: !include json/cmdaa.json