#%RAML 0.8
title: API Using media type in the URL
baseUri: message://command/handler/message/service1
version: v1
/structure.handler.command:
  post:
    body:
        application/vnd.structure.cmdaa+json:
