#%RAML 0.8
title: Event processor
baseUri: message://event/listener/message/example
version: v1
/people.event:
  post:
    body:
        application/vnd.people.eventbb+json:
            schema: !include json/schema/people.eventbb.json
            example: !include json/eventbb.json

/example.event:
  post:
    body:
        application/vnd.example.eventaa+json:
            schema: !include json/schema/example.eventaa.json
            example: !include json/eventaa.json