#%RAML 0.8
title: Example Service
baseUri: http://localhost:8080/rest-client-generator/command/api/rest/example

/users/{userId}:
  post:
    description: |
        ...
        (mapping):
            requestType: application/vnd.people.create-user+json
            name: people.create-user
        ...
    body:
      application/vnd.people.create-user+json:

  put:
    description: |
        ...
        (mapping):
            requestType: application/vnd.people.update-user+json
            name: people.update-user
        ...
    body:
      application/vnd.people.update-user+json:

  patch:
    description: |
        ...
        (mapping):
            requestType: application/vnd.people.modify-user+json
            name: people.modify-user
        ...
    body:
      application/vnd.people.modify-user+json:

/groups/{groupId}:
  post:
    description: |
        ...
        (mapping):
            requestType: application/vnd.people.group+json
            name: people.create-group
        ...
    body:
      application/vnd.people.group+json:
    responses:
        200:
            body:
                application/vnd.people.group+json:

  put:
    description: |
        ...
        (mapping):
            requestType: application/vnd.people.group+json
            name: people.update-group
        ...
    body:
      application/vnd.people.group+json:
    responses:
        200:
            body:
                application/vnd.people.group+json:

  patch:
    description: |
        ...
        (mapping):
            requestType: application/vnd.people.group+json
            name: people.modify-group
        ...
    body:
      application/vnd.people.group+json:
    responses:
        200:
            body:
                application/vnd.people.group+json:
