#%RAML 0.8
title: Example Service
baseUri: http://localhost:8080/rest-client-generator/query/controller/rest/example

/users/{userId}:
  get:
    description: |
        ...
        (mapping):
            responseType: application/vnd.people.query.user1+json
            name: people.get-user1
        (mapping):
            responseType: application/vnd.people.query.user2+json
            name: people.get-user2
        ...
    responses:
        200:
            body:
                application/vnd.people.query.user1+json:
                application/vnd.people.query.user2+json:

/users:
  get:
    description: |
        ...
        (mapping):
            responseType: application/vnd.people.users+json
            name: people.search-users
        ...
    queryParameters:
        surname:
            type: string
    responses:
        200:
            body:
                application/vnd.people.users+json:
  post:
    description: |
        ...
        (mapping):
            requestType: application/vnd.people.post-search-users+json
            name: people.post-search-users
        ...
    body:
      application/vnd.people.post-search-users+json:
    responses:
        200:
            body:
                application/vnd.people.users+json:

