#%RAML 0.8
title: Example Service
baseUri: http://localhost:8080/rest-client-generator/command/api/rest/example

/users/{userId}:
  post:
    description: |
        ...
        (mapping):
            requestType: application/vnd.people.update-user+json
            name: people.post-update-user
        ...
    body:
      application/vnd.people.update-user+json:

  put:
    description: |
        ...
        (mapping):
            requestType: application/vnd.people.update-user+json
            name: people.put-update-user
        ...
    body:
      application/vnd.people.update-user+json:

