#%RAML 0.8
title: API Using media type in the URL
version: v1
/structure.controller.command:
  post:
    body:
        application/vnd.structure.command.commanda+json:
        application/vnd.structure.command.commandb+json: