#%RAML 0.8
title: API Using media type in the URL
baseUri: message://command/controller/message/service1
version: v1

/structure.controller.commands:
  post:
    body:
        application/vnd.structure.commands.commanda+json:
        application/vnd.structure.commands.commandb+json: