#%RAML 0.8
title: API Using media type in the URL
baseUri: message://command/controller/message/service1
version: v1

/structure.controller.command:
  post:
    body:
        application/vnd.structure.command.commanda+json:
        application/vnd.structure.command.commandb+json:
