#%RAML 0.8
title: API Using media type in the URL
baseUri: message://command/handler/message/publish
version: v1
/publish.handler.command:
  post:
    body:
        application/vnd.publish.command.add-robot+json:
            schema: !include json/schema/publish.command.add-robot.json
            example: !include json/publish.command.add-robot.json
