#%RAML 0.8
title: API Using media type in the URL
baseUri: message://command/controller/message/cakeshop
version: v1
/cakeshop.controller.command:
  post:
    body:
        application/vnd.cakeshop.add-recipe+json:
            schema: !include json/schema/cakeshop.add-recipe.json
            example: !include json/add-recipe.json

        application/vnd.cakeshop.remove-recipe+json:
                    schema: !include json/schema/cakeshop.remove-recipe.json
                    example: !include json/remove-recipe.json

        application/vnd.cakeshop.make-cake+json:
            schema: !include json/schema/cakeshop.make-cake.json
            example: !include json/make-cake.json

        application/vnd.cakeshop.order-cake+json:
            schema: !include json/schema/cakeshop.order-cake.json
            example: !include json/order-cake.json