#%RAML 0.8
title: API Using media type in the URL
baseUri: message://command/controller/message/cakeshop
version: v1
/example.controller.command:
  post:
    body:
        application/vnd.example.add-recipe+json:
            schema: !include json/schema/example.add-recipe.json
            example: !include json/add-recipe.json

        application/vnd.example.remove-recipe+json:
                    schema: !include json/schema/example.remove-recipe.json
                    example: !include json/remove-recipe.json

        application/vnd.example.make-cake+json:
            schema: !include json/schema/example.make-cake.json
            example: !include json/make-cake.json

        application/vnd.example.order-cake+json:
            schema: !include json/schema/example.order-cake.json
            example: !include json/order-cake.json