#%RAML 0.8
title: API Using media type in the URL
baseUri: message://command/controller/message/cakeshop
version: v1
/example.controller.command:
  post:
    body:
        application/vnd.example.add-recipe+json:
            schema: !include json/schema/command_controller/example.add-recipe.json
            example: !include json/add-recipe.json

        application/vnd.example.remove-recipe+json:
            schema: !include json/schema/command_controller/example.remove-recipe.json
            example: !include json/remove-recipe.json

        application/vnd.example.make-cake+json:
            schema: !include json/schema/command_controller/example.make-cake.json
            example: !include json/make-cake.json

        application/vnd.example.order-cake+json:
            schema: !include json/schema/command_controller/example.order-cake.json
            example: !include json/order-cake.json

        application/vnd.example.rename-recipe+json:
            schema: !include json/schema/command_controller/example.rename-recipe.json
            example: !include json/rename-recipe.json

        application/vnd.example.upload-photograph+json:
            schema: !include json/schema/command_controller/example.upload-photograph.json
            example: !include json/upload-photograph.json