#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/processor/message/cakeshop
version: v1
/example.event:
  post:
    body:
        application/vnd.example.events.recipe-added+json:
            schema: !include json/schema/example.events.recipe-added.json
            example: !include json/recipe-added.json

        application/vnd.example.events.cake-made+json:
            schema: !include json/schema/example.events.cake-made.json
            example: !include json/cake-made.json