#%RAML 0.8
title: Example Service
baseUri: http://localhost:8080/rest-adapter-generator/command/api/rest/example
version: v0.1
mediaType: application/json
protocols: [ HTTP, HTTPS ]

/users/{userId}:
  description: |
    Create user or Update user
  post:
    description: |
        ...
        (mapping):
            requestType: application/vnd.people.user+json
            name: people.create-user
        ...
    body:
        application/vnd.people.user+json:
            schema: !include json/schema/people.user.json
            example: !include json/create-user.json
    responses:
        202:
            body:
                application/vnd.people.user+json:
                  schema: !include json/schema/people.user.json