#%RAML 0.8
title: Example Service
baseUri: http://localhost:8080/rest-adapter-generator/query/api/rest/example
version: v0.1
mediaType: application/json
protocols: [ HTTP, HTTPS ]

/users/{userId}:
  description: |
    Create user or Update user
  post:
    description: |
        ...
        (mapping):
            requestType: application/vnd.people.user+json
            name: people.create-user
        (mapping):
            requestType: application/vnd.people.modified-user+json
            name: people.update-user
        (mapping):
            requestType: application/vnd.people.link-user+json
            name: people.link-user
        ...
    body:
        application/vnd.people.user+json:
            schema: !include json/schema/people.user.json
            example: !include json/create-user.json
        application/vnd.people.modified-user+json:
            schema: !include json/schema/people.modified-user.json
            example: !include json/update-user.json
        application/vnd.people.link-user+json: !!null
  get:
    description: |
        ...
        (mapping):
            responseType: application/vnd.people.user+json
            name: people.get-user
        (mapping):
            responseType: application/vnd.people.user-summary+json
            name: people.get-user-summary
        ...
    responses:
        200:
            body:
                application/vnd.people.user+json:
                application/vnd.people.user-summary+json:

/users:
  description: |
    Search users
  get:
    description: |
          ...
          (mapping):
              responseType: application/vnd.people.users+json
              name: people.search-users
          ...
    queryParameters:
        lastname:
            type: string
            required: true
        firstname:
            type: string
            required: false
        age:
            type: integer
            required: false
        height:
            type: number
            required: false
        married:
            type: boolean
            required: false


    responses:
        200:
            body:
                application/vnd.people.users+json:
