#%RAML 0.8
title: Example Service
baseUri: http://localhost:8080/rest-adapter-generator/command/api/rest/example
version: v0.1
mediaType: application/json
protocols: [ HTTP, HTTPS ]

/photographs/{userid}:
  post:
    description: |
      Upload User Photograph
      ...
      (mapping):
          requestType: multipart/form-data
          name: people.upload-photograph
      ...
    body:
        multipart/form-data:
            formParameters:
                photoId:
                    description: Photograph of user
                    type: file
    responses:
        202:
            description: Request accepted
        400:
            description: Bad Request
        500:
            description: Internal Server Error
