@startuml
skinparam backgroundColor white
skinparam defaultFontName Arial
skinparam defaultFontsize 16

participant "CommandHandler" as CommandHandler
participant "SnapshotAwareEnvelopeEventStream" as SnapshotAwareEnvelopeEventStream
participant "SnapshotAwareEventStreamManager" as SnapshotAwareEventStreamManager
participant "SnapshotService" as SnapshotService
participant "SnapshotRepository" as SnapshotRepository
participant "SnapshotStrategy" as SnapshotStrategy

CommandHandler -> SnapshotAwareEnvelopeEventStream: append(streamid,events)
SnapshotAwareEnvelopeEventStream -> SnapshotAwareEventStreamManager: append(streamid,events)
SnapshotAwareEventStreamManager -> SnapshotService: attemptAggregateStore(Aggregate,Version)
activate SnapshotService
SnapshotService -> SnapshotStrategy: shouldCreateSnapshot(Oldversion,NewVersion)
activate SnapshotStrategy
SnapshotService <- SnapshotStrategy: true/false
deactivate SnapshotStrategy
SnapshotService ->  SnapshotRepository: if (true) storeSnapshot (AggregateSnapshot)
deactivate SnapshotService
@enduml
